# Generated by Django 3.1 on 2021-09-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychain',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
