# Generated by Django 3.2.7 on 2021-09-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0003_alter_supplychain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplychain',
            name='details',
            field=models.TextField(default='details'),
            preserve_default=False,
        ),
    ]
