# Generated by Django 3.1 on 2021-11-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0004_supplychain_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychain',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
