# Generated by Django 3.2.9 on 2021-11-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0005_auto_20211103_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
