# Generated by Django 4.0.3 on 2022-04-02 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplychain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('generic_attribute', models.JSONField(blank=True, null=True)),
                ('supply_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.supplychain')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('attributes', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ethereum_address', models.CharField(max_length=255)),
                ('generic_attribute_data', models.JSONField(blank=True, null=True)),
                ('connected_supply_chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instace_supply_chain', to='supplychain.supplychain')),
                ('connecting_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_entity', to='entities.entity')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_entity', to='entities.entity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_destination', to='entities.entity')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_source', to='entities.entity')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='entities.template'),
        ),
    ]
