# Generated by Django 4.0.3 on 2022-04-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='generic_attribute',
            new_name='generic_attributes',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='generic_attribute_data',
            new_name='generic_attributes_data',
        ),
    ]
