# Generated by Django 3.2.7 on 2021-09-26 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20210908_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='genericattributes',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='genericattributes',
            name='value',
        ),
        migrations.AddField(
            model_name='genericattributes',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.entity'),
        ),
        migrations.AddField(
            model_name='genericattributes',
            name='type',
            field=models.CharField(choices=[('Numeric', 'Numeric'), ('String', 'String'), ('Date', 'Date')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genericattributes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='GenericAttributesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('generic_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.genericattributes')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.instance')),
            ],
        ),
    ]
