# Generated by Django 3.2.7 on 2021-09-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20210926_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAttributeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='genericattributes',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_attributes', to='entities.entity'),
        ),
        migrations.DeleteModel(
            name='GenericAttributesData',
        ),
        migrations.AddField(
            model_name='genericattributedata',
            name='generic_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.genericattributes'),
        ),
        migrations.AddField(
            model_name='genericattributedata',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_attribute_data', to='entities.instance'),
        ),
    ]
