# Generated by Django 3.2.7 on 2021-09-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20210926_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_destination', to='entities.entity')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_source', to='entities.entity')),
            ],
        ),
    ]
