# Generated by Django 3.2.7 on 2021-09-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericattributes',
            name='type',
            field=models.CharField(choices=[('Alphanumeric', 'Alphanumeric'), ('String', 'String'), ('Date', 'Date'), ('Number', 'Number')], max_length=12, null=True),
        ),
    ]
