# Generated by Django 3.2.7 on 2021-10-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_alter_genericattributes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_source',
            field=models.BooleanField(default=False),
        ),
    ]
