# Generated by Django 3.2.7 on 2021-10-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_entity_is_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='instance_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance_entity', to='entities.entity'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_entity', to='entities.entity'),
        ),
    ]
