# Generated by Django 3.2.7 on 2021-10-05 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0004_supplychain_details'),
        ('entities', '0008_auto_20211005_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='instance_entity',
        ),
        migrations.AddField(
            model_name='instance',
            name='supply_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instace_supply_chain', to='supplychain.supplychain'),
        ),
    ]
