# Generated by Django 3.2.7 on 2021-10-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0004_supplychain_details'),
        ('entities', '0009_auto_20211005_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='is_source',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='supply_chain',
        ),
        migrations.AddField(
            model_name='instance',
            name='connected_supply_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instace_supply_chain', to='supplychain.supplychain'),
        ),
        migrations.AddField(
            model_name='instance',
            name='connecting_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_entity', to='entities.entity'),
        ),
    ]
