# Generated by Django 3.2.7 on 2021-10-27 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0010_auto_20211005_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
